namespace VED.Physics
{
    public static class Enums
    {
        public enum PhysicsColliderType
        {
            NONE   ,
            S      ,
            S_HL   ,
            S_HR   ,
            S_HT   ,
            S_HB   ,
            S_HMH  ,
            S_HMV  ,
            S_1TL  ,
            S_1TR  ,
            S_1TT  ,
            S_1TB  ,
            S_1TMH ,
            S_1TMV ,
            S_2TL  ,
            S_2TR  ,
            S_2TT  ,
            S_2TB  ,
            S_2TMH ,
            S_2TMV ,
            C_BL   ,
            C_BR   ,
            C_TL   ,
            C_TR   ,
            T_BL   ,
            T_BR   ,
            T_TL   ,
            T_TR   ,
            T_HBL1 ,
            T_HBL2 ,
            T_HBL3 ,
            T_HBR1 ,
            T_HBR2 ,
            T_HBR3 ,
            T_VBL1 ,
            T_VBL2 ,
            T_VBL3 ,
            T_VBR1 ,
            T_VBR2 ,
            T_VBR3 ,
            T_RBL1 ,
            T_RBL2 ,
            T_RBR1 ,
            T_RBR2 ,
            T_RTL1 ,
            T_RTL2 ,
            T_RTR1 ,
            T_RTR2 ,
            TS_HBL ,
            TS_HBR ,
            TS_HTL ,
            TS_HTR ,
            TS_VBL ,
            TS_VBR ,
            TS_VTL ,
            TS_VTR
        }
    }
}